export type typeApiMateria = { materia: string, creditos: number }

const apiMateria: typeApiMateria[] = [
   { materia: 'Selecciona Tu Materia', creditos: 0 },
   { materia: 'Fundamentos del Computador', creditos: 4 },
   { materia: 'Introduccion a la elaboracion de Algoritmos', creditos: 4 },
   { materia: 'Historia Universal', creditos: 3 },
   { materia: 'Precalculo', creditos: 5 },
   { materia: 'Redaccion Castellana', creditos: 4 },
   { materia: 'Orientacion Institucional', creditos: 1 },
   { materia: 'Etica 1', creditos: 3 },
   { materia: 'Historia Dominicana', creditos: 3 },
   { materia: 'Calculo Diferencial', creditos: 5 },
   { materia: 'Calculo Integral', creditos: 5 },
   { materia: 'Fundamentos de Programacion', creditos: 4 },
   { materia: 'Etica 2', creditos: 3 },
   { materia: 'Introduccion a la Base de Datos', creditos: 4 },
   { materia: 'Contabilidad Financiera', creditos: 4 },
   { materia: 'Probabilidad y Estadistica', creditos: 3 },
   { materia: 'Programacion 1', creditos: 4 },
   { materia: 'Analisis y Diseno de Sistemas', creditos: 4 },
   { materia: 'Fisica General', creditos: 4 },
   { materia: 'Laboratorio Fisica General', creditos: 1 },
   { materia: 'Etica 3', creditos: 3 },
   { materia: 'Diseno Centrado en el Usuario', creditos: 4 },
   { materia: 'Metodologia de la investigacion', creditos: 3 },
   { materia: 'Base de Datos avanzada', creditos: 4 },
   { materia: 'Programacion 2', creditos: 4 },
   { materia: 'Inteligencia Artificial', creditos: 4 },
   { materia: 'Auditoria Informatica ', creditos: 4 },
   { materia: 'Programacion 3', creditos: 4 },
   { materia: 'Mineria de Datos e Inteligencia de Negocios', creditos: 4 },
   { materia: 'Fundamentos de Electronica', creditos: 4 },
   { materia: 'Laboratorio Fundamentos de Electronica', creditos: 1 },
   { materia: 'Programacion Web', creditos: 4 },
   { materia: 'Electiva 1', creditos: 3 },
   { materia: 'Programacion Paralela', creditos: 4 },
   { materia: 'Introduccion a la Ingenieria de Software', creditos: 4 },
   { materia: 'Electiva 2', creditos: 3 },
   { materia: 'Desarrollo de Emprendedores', creditos: 3 },
   { materia: 'Ingles Tecnico', creditos: 4 },
   { materia: 'Estructura de Datos', creditos: 4 },
   { materia: 'Administracion de Proyectos de Software', creditos: 4 },
   { materia: 'Introduccion al Desarrollo de Aplicaciones Moviles', creditos: 4 },
   { materia: 'Plan de Negocios', creditos: 3 },
   { materia: 'Proyecto Final TDS', creditos: 3 },
]
export default apiMateria